### ISSUE TITLE
PHP deprecation notice in 7.3

### ISSUE THREAD

**Issue by schliflo** [Asenar/less.php#2]
I'm getting the following notice using PHP 7.3 
```
NOTICE: PHP message: PHP Deprecated:  strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /app/vendor/wikimedia/less.php/lib/Less/SourceMap/Generator.php on line 172
```

Doesn't seem urgent but hast to be fixed eventually.
Affected line:
https://github.com/Asenar/less.php/blob/master/lib/Less/SourceMap/Generator.php#L172

**Comment by Asenar** [comment]
Hi,
feel free to propose a pull request :)

**Comment by schliflo** [comment]
I'll have to look at it next week :)

**Comment by Asenar** [comment]
(sorry I did some mistakes in my git history, this made github misunderstood some stuffs)

**Comment by schliflo** [comment]
no worries :)

**Comment by schliflo** [comment]
The fix is also in the wikimedia fork now: https://github.com/wikimedia/less.php/pull/8 :) - closing as this is resolved as far as I'm concerned
