### ISSUE TITLE
How is this repo related to wikimedia/less.php

### ISSUE THREAD

**Issue by schliflo** [Asenar/less.php#4]
I was wondering how this repo is related to https://github.com/wikimedia/less.php
Is this another fork or is development here somehow related to wikimedia?

**Comment by Asenar** [comment]
When I started that fork I set `asenar/less.php` to make it work in my project. Then, the author of that lib gave me some partial access so I put again the name `oyejorge` and made some update (v1.7.0.14), but some access (long time ago, I don't remember) were missing to update the composer build. Then I found a fork that was better than mine and merged lot of interesting things so I pulled them in my repo, and I didn't paid attention to the composer.json name update :/ 

As I m still currently stuck with php5 and the lib works in 1.7.0.14, and the 1.8 changes  The changes made by the wikimedia fork is `continue` being replaced by `break` in `Less/Exception/Chunk.php`.

You can use their package if your prefer.
https://packagist.org/packages/wikimedia/less.php

(I may update my repo later to use again `asenar` name if there is useful changes, and follow the semantic version introduced in 1.8.0 as mentionned in CHANGES.md :)

**Comment by schliflo** [comment]
Thx for clarifying - I'm already using their version then as i just looked at the composer.json
